debug: false
host: "${THALES_CTM_HOST}"
username: "${THALES_CTM_USERNAME}"
password: "${THALES_CTM_PASSWORD}"
domain: "root"
verify_ssl: false
certificate_login: false
ca_certfile: "certs/thales_ctm/dummy_ca_cert.pem"
auth_certfile: "certs/thales_ctm/dummy_cert.pem"
auth_keyfile: "certs/thales_ctm/dummy_key.pem"
key_wrap_algorithm: "AES/AESKEYWRAPPADDING"
